### ISSUE TITLE
One Arduino to for RF + Ethernet

### ISSUE THREAD

**Issue by tedstriker** [homeautomationyay/OpenHab-RFM69#1]
Hello Eric,

As I couldn't find another way to reach you, I'll try this. I'd like to know what issues you ran into while trying to use a single arduino as RF-hub <-> Ethernet/MQTT bridge?

Thx
Ted

**Comment by tsaitsai** [comment]
Ted,
It's probably possible to use the same Arduino for the ethernet gateway as the RFM gateway, but I couldn't figure out how to tell the RFM library to use a different Device Select pin.  The defaults on both the RFM and the Wiznet 5100 library use the same device select pin for SPI comms.

But having separate arduinos adds a certain amount of flexibility.  You can replace the RFM arduino with whatever wireless Arduino you want.  You can go bluetooth, for example.

**Comment by tedstriker** [comment]
Hi Eric, thank you for your response and sorry for my late reply.

**Comment by sosandroid** [comment]
One idea to move around this is using one Udoo board to run both OpenHab and the Arduino + RFM69.
As the Linux section & the arduino section are communicating through Serial, it is quite easy to send to OpenHab data using its Serial listener plugin.
The direct consequence is we don't need anymore the MQTT broker.

Just an idea
